[package]
name = "jikan-rs"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
reqwest = { version = "0.12.15", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

